all:
	g++ main.cpp ./code/md_private.cpp ./code/Vector2.cpp ./code/md_public.cpp -o ../MakeMD.out
	../MakeMD.out
	python3 ../ShowMD.py
	
compile:
	g++ main.cpp ./code/md_private.cpp ./code/Vector2.cpp ./code/md_public.cpp -o ../MakeMD.out

show:
	python3 ../ShowMD.py